In [1]:
import pandas as pd
import plotly.graph_objs as go
import plotly.offline as pyo

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/Pierian-Data/Plotly-Dashboards-with-Dash/master/SourceData/nst-est2017-alldata.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,NAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2015,RDOMESTICMIG2016,RDOMESTICMIG2017,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017
0,10.0,0,0,0.0,United States,308745538.0,308758105.0,309338421.0,311644280.0,313993272.0,...,0.000000,0.000000,0.000000,2.720900,2.920371,2.883643,3.173228,3.516743,3.513394,3.423941
1,20.0,1,0,0.0,Northeast Region,55317240.0,55318350.0,55388349.0,55642659.0,55860261.0,...,-6.103092,-6.619089,-5.559570,1.467950,0.779137,0.605873,-0.082832,-0.903931,-1.307503,-0.288930
2,20.0,2,0,0.0,Midwest Region,66927001.0,66929794.0,66973360.0,67141501.0,67318295.0,...,-3.458531,-3.307295,-2.304640,-1.187519,-1.010696,-0.120354,-0.752477,-1.323952,-1.160735,-0.191323
3,20.0,3,0,0.0,South Region,114555744.0,114563024.0,114869241.0,116060993.0,117291728.0,...,3.788037,3.592695,2.900528,5.544289,5.831747,5.362083,6.317310,7.336162,7.113818,6.304010
4,20.0,4,0,0.0,West Region,71945553.0,71946937.0,72107471.0,72799127.0,73522988.0,...,1.613450,2.099001,1.475519,2.798796,3.521423,3.396627,4.163576,5.067452,5.488965,4.737979

In [5]:
df2=df[df['DIVISION']=='1']

In [6]:
df2.set_index('NAME',inplace=True)

In [7]:
df2

,SUMLEV,REGION,DIVISION,STATE,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,...,RDOMESTICMIG2015,RDOMESTICMIG2016,RDOMESTICMIG2017,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017
NAME,,,,,,,,,,,,,,,,,,,,,
Connecticut,40.0,1,1,9.0,3574097.0,3574114.0,3580171.0,3591927.0,3597705.0,3602470.0,...,-8.376089,-8.106331,-6.206914,0.993851,-0.542726,-0.420268,-2.479362,-3.464252,-3.112421,-1.257548
Maine,40.0,1,1,23.0,1328361.0,1328362.0,1327568.0,1327968.0,1328101.0,1327975.0,...,-0.781424,1.807361,4.032798,0.685361,0.178459,0.392308,1.301528,0.389959,3.000731,5.216532
Massachusetts,40.0,1,1,25.0,6547629.0,6547808.0,6564943.0,6612178.0,6659627.0,6711138.0,...,-3.270088,-4.423353,-3.374712,4.364383,4.266338,5.211370,4.538697,3.276287,2.261905,3.246090
New Hampshire,40.0,1,1,33.0,1316470.0,1316460.0,1316700.0,1318345.0,1320923.0,1322622.0,...,-0.850002,1.333509,3.500622,-0.403029,0.632751,0.061281,3.793602,0.852258,3.037729,5.170643
Rhode Island,40.0,1,1,44.0,1052567.0,1052945.0,1053169.0,1052154.0,1052761.0,1052784.0,...,-4.218510,-4.093718,-3.640649,-2.170688,-0.991964,-1.139847,1.029624,0.368598,0.526146,0.891742
Vermont,40.0,1,1,50.0,625741.0,625741.0,625842.0,626210.0,625606.0,626044.0,...,-3.415672,-3.615938,-1.472321,-0.333852,-1.915617,0.131027,-1.313404,-1.932614,-2.115708,0.024058

In [8]:
list_pop_col=[col for col in df2.columns if col.startswith('POP')]

In [11]:
df2=df2[list_pop_col]

In [12]:
df2

,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017
NAME,,,,,,,,
Connecticut,3580171.0,3591927.0,3597705.0,3602470.0,3600188.0,3593862.0,3587685.0,3588184.0
Maine,1327568.0,1327968.0,1328101.0,1327975.0,1328903.0,1327787.0,1330232.0,1335907.0
Massachusetts,6564943.0,6612178.0,6659627.0,6711138.0,6757925.0,6794002.0,6823721.0,6859819.0
New Hampshire,1316700.0,1318345.0,1320923.0,1322622.0,1328684.0,1330134.0,1335015.0,1342795.0
Rhode Island,1053169.0,1052154.0,1052761.0,1052784.0,1054782.0,1055916.0,1057566.0,1059639.0
Vermont,625842.0,626210.0,625606.0,626044.0,625665.0,624455.0,623354.0,623657.0

In [13]:
data=[go.Scatter(x=df2.columns,y=df2.loc[name],mode='lines',name=name) for name in df2.index]

In [14]:
pyo.plot(data)

'temp-plot.html'